name: pycep
base: core18
version: git
summary: A simple application that get information from an address
description: |
  This simple cli is used to get some information from an address like cep
  number, steet name, city, etc.
architectures:
  - build-on: [amd64, arm64]

grade: stable
confinement: strict

parts:
  pycep:
    plugin: python
    source: .
    python-packages:
      - click
      - requests

apps:
  pycep:
    command: bin/pycep
    plugs:
      - home
      - network